# Form implementation generated from reading ui file 'd:\флешка\Yandex_Lyceum\lesson_7\untitled.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(425, 243)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button.setGeometry(QtCore.QRect(210, 50, 75, 23))
        self.button.setObjectName("button")
        self.filenameEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.filenameEdit.setGeometry(QtCore.QRect(70, 50, 131, 20))
        self.filenameEdit.setObjectName("filenameEdit")
        self.maxEdit = QtWidgets.QLabel(parent=self.centralwidget)
        self.maxEdit.setGeometry(QtCore.QRect(20, 90, 141, 16))
        self.maxEdit.setObjectName("maxEdit")
        self.minEdit = QtWidgets.QLabel(parent=self.centralwidget)
        self.minEdit.setGeometry(QtCore.QRect(20, 120, 131, 16))
        self.minEdit.setObjectName("minEdit")
        self.avgEdit = QtWidgets.QLabel(parent=self.centralwidget)
        self.avgEdit.setGeometry(QtCore.QRect(50, 150, 111, 16))
        self.avgEdit.setObjectName("avgEdit")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 81, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(160, 90, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 120, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 150, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 425, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button.setText(_translate("MainWindow", "Рассчитать"))
        self.maxEdit.setText(_translate("MainWindow", "Максимальное значение:"))
        self.minEdit.setText(_translate("MainWindow", "Минимальное значение:"))
        self.avgEdit.setText(_translate("MainWindow", "Среднее значение:"))
        self.label_4.setText(_translate("MainWindow", "Имя файла"))
